name: Add tag

run-name: Add tag:${{ github.ref_name }}(${{ github.event.head_commit.message }})

on:
  push:
    branches:
      - 'main'

jobs:
  add-tag:
    runs-on: ubuntu-22.04

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: .traps-github-action

      - name: Add tag
        uses: ./.traps-github-action/ros2-add-tag
        with:
          path: .traps-github-action

